"""Hand codes for the 150 residual 'other' rows in the stratified 400-FP sample.

Keys are stripped utterance strings as they appear in the workbooks.
These override the rule-based codebook for the sample only.
"""
from __future__ import annotations

# ruff: noqa: E501
HAND_CODES: dict[str, str] = {
    "Can I, model?": "play_materials",
    "Carrots for who?": "object_naming",
    "Carry. Carry. Carry.": "classroom_management",
    "I can't see.": "deictic_attention",
    "I saw that.": "deictic_attention",
    "I see you!": "deictic_attention",
    "Is what monster?": "object_naming",
    "It's a butterfly.": "borderline_science",
    "It's a robot.": "object_naming",
    "It's my nose.": "object_naming",
    "It's not broken.": "other",
    "It's not working.": "other",
    "It's so long.": "other",
    "Just fly it.": "play_materials",
    "Let me see": "deictic_attention",
    "No cooler hair.": "social_affect",
    "No, not always.": "other",
    "Not a puppy.": "object_naming",
    "On a train.": "object_naming",
    "Open your hand": "classroom_management",
    "That's a box.": "object_naming",
    "There is one.": "counting_math",
    "They're just flat.": "shape_color",
    "Watch your arm.": "classroom_management",
    "We can't see.": "deictic_attention",
    "Where are you?": "social_affect",
    "And they eat more.": "borderline_science",
    "Can I have more?": "classroom_management",
    "How does that work?": "borderline_science",
    "How's it gonna happen?": "borderline_science",
    "It has 12 screens.": "other",
    "It's a dinosaur magnet.": "borderline_science",
    "It's a play girl.": "play_materials",
    "It's getting bigger now.": "borderline_science",
    "Oh, it's a gun.": "object_naming",
    "Papers in the trash.": "classroom_management",
    "Push your arm through.": "classroom_management",
    "That was my foot.": "social_affect",
    "That's a tree cracks.": "borderline_science",
    "That's not a two.": "counting_math",
    "That's still only four.": "counting_math",
    "The tree doesn't fall.": "borderline_science",
    "They can connect together.": "borderline_science",
    "Well, we have two.": "counting_math",
    "What are we eating?": "other",
    "What do you see?": "deictic_attention",
    "Where is this going?": "other",
    "Who's at the door?": "social_affect",
    "Yeah, I saw that.": "deictic_attention",
    "You go under, okay?": "classroom_management",
    "the tie on top.": "object_naming",
    "A red bear? Red bird.": "object_naming",
    "Aiden is looking for gray.": "shape_color",
    "All right, we have Lily.": "classroom_management",
    "And she had gloves on.": "other",
    "Can I have a V?": "literacy",
    "Can I hold the door?": "classroom_management",
    "Come on, it's not here.": "classroom_management",
    "I do have a bear.": "object_naming",
    "I'm a mama owl baby.": "borderline_science",
    "I'm going to do it.": "classroom_management",
    "I'm going to the side.": "classroom_management",
    "It's going to dry out.": "borderline_science",
    "It's in a big ponytail.": "other",
    "Let me see your hair.": "social_affect",
    "Michelle, that was your feet.": "social_affect",
    "Okay, I saw my thing.": "deictic_attention",
    "One. Two. Three. Four. Five.": "counting_math",
    "Right, so that's going down.": "other",
    "See what the sides are.": "shape_color",
    "She did not say chicken.": "object_naming",
    "So where does it go?": "borderline_science",
    "Tell him this is science.": "classroom_management",
    "There are billions of people.": "other",
    "There's lots to pick from.": "classroom_management",
    "This can be the ears.": "object_naming",
    "This is also a car.": "object_naming",
    "Well, I mean they are.": "other",
    "What's going on up here?": "deictic_attention",
    "Yeah, that was a lot.": "other",
    "Yes, it was a bird.": "borderline_science",
    "You can't pull it down.": "classroom_management",
    "And that's what we're looking at.": "deictic_attention",
    "But you can leave it here,": "classroom_management",
    "Do you have a Christmas tree?": "object_naming",
    "He's bigger than the other two.": "counting_math",
    "I can make stems, Ms. Annie.": "borderline_science",
    "I need to see the bugger.": "borderline_science",
    "I think we are eating it.": "other",
    "I'm a baby, I'm a baby.": "social_affect",
    "I'm going to throw a ball.": "play_materials",
    "I'm looking at what we have.": "deictic_attention",
    "It needs to be facing out.": "classroom_management",
    "Jamal, this is the tree trunk.": "borderline_science",
    "Let me see if she's bleeding.": "other",
    "Ms. Elizabeth, what are we eating?": "other",
    "No, he's got his own food.": "other",
    "No, no, I see two fruits.": "counting_math",
    "Now his feet were all white.": "shape_color",
    "Okay, go on your side first.": "classroom_management",
    "She started taking them all out.": "classroom_management",
    "So we can see the blue.": "shape_color",
    "So where do you get that?": "other",
    "That's the same thing, a car.": "object_naming",
    "And it needs another flat side here.": "shape_color",
    "Did you see this hand right there?": "deictic_attention",
    "Do you think she'll like that one?": "social_affect",
    "I have three nails on my feet.": "other",
    "I made a tree for my dog.": "play_materials",
    "I'm going to use the white one.": "shape_color",
    "Is your thing from last year accurate?": "other",
    "Let's leg up for a little bit": "classroom_management",
    "Oh, all the way to our spot.": "classroom_management",
    "Oh, you're going to make a line.": "shape_color",
    "Okay, put your wet clothes in there.": "classroom_management",
    "This is what up here looks like.": "deictic_attention",
    "We have plenty of stuff I copied.": "literacy",
    "What are you putting in there now?": "classroom_management",
    "Where's my rope? I cannot see it.": "deictic_attention",
    "You're not flying an airplane, making airplanes.": "play_materials",
    "I guess it needs to be facing out.": "classroom_management",
    "So one of them does not have two.": "counting_math",
    "The front, the back, the top, the side.": "shape_color",
    "What are you doing for a vest on?": "classroom_management",
    "What else do you need me to do?": "classroom_management",
    "What type of egg? Like an Easter egg?": "object_naming",
    "so you can actually see where you're circling.": "shape_color",
    "But my question is, what's going to happen now?": "borderline_science",
    "I'm waiting to see your eyes looking at me.": "classroom_management",
    "Okay, now, let me get you a baby wipe.": "classroom_management",
    "We've never seen any ducklings as large as you.": "borderline_science",
    "Actually I think that's been, oh no there's one more.": "counting_math",
    "Here you go can i make a tree for you?": "play_materials",
    "It's just a little device that we're going to use.": "other",
    "It's kind of like a beautiful, kind of straight house.": "other",
    "This shows 11 active beacons, even though there's only 10.": "other",
    "they're going to dry out. You can hang on now.": "classroom_management",
    "If I buy some flowers, I got lots of many kinds.": "borderline_science",
    "If you feel that one more time, you're not getting wet.": "classroom_management",
    "Mother Goat put the rocks she collected carefully inside the hoof.": "literacy",
    "Noah, hurry and finish that, and then come see me, okay?": "classroom_management",
    "No, that has that cheese that you can't have. I want yogurt.": "other",
    "She could go so many ways. The airplane, the train, the car.": "object_naming",
    "that many data today if we can't get it to turn on.": "other",
    "shape where all points around the outside are the same distance from its": "shape_color",
    "fruits to collect and you have to use your spoon to scoop your fruit okay all": "play_materials",
    "How did that happen? Yeah, how did it happen? I was there. I was there. It's right here.": "borderline_science",
    "This always happens to me. I'm trying to grab something, but the stuff at the top doesn't let me.": "other",
    "side in, put your right side in, put your right side in, put your right side in, put your": "classroom_management",
}


def apply_hand_code(utt: str, fallback: str) -> str:
    key = (utt or "").strip()
    return HAND_CODES.get(key, fallback)
